name: Daily Expense Reminder

on:
  workflow_dispatch:

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send OneSignal Notification
        run: |
          RESPONSE=$(curl -s -X POST "https://api.onesignal.com/notifications" \
            -H "Authorization: Bearer ${{ secrets.ONESIGNAL_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "app_id":"${{ secrets.ONESIGNAL_APP_ID }}",
              "included_segments": ["Total Subscriptions"],
              "target_channel":"push",
              "headings":{
                "en":"🧪 API Test"
              },
              "contents":{
                "en":"Testing direct Subscription ID notification."
              },
              "url":"https://naveensiriveri24-jcoder.github.io/"
            }')

          echo "$RESPONSE"
