name: Daily Expense Reminder

on:
  workflow_dispatch:

  schedule:
    - cron: '30 13 * * *'

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Check App ID
        run: |
          echo "App ID length: ${#APP_ID}"
        env:
          APP_ID: ${{ secrets.ONESIGNAL_APP_ID }}
      - name: Send OneSignal Notification
        run: |
          curl -X POST https://api.onesignal.com/notifications \
            -H "Authorization: Bearer ${{ secrets.ONESIGNAL_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "app_id":"${{ secrets.ONESIGNAL_APP_ID }}",
              "included_segments":["Subscribed Users"],
              "headings":{"en":"💰 ExpenseFlow Reminder"},
              "contents":{"en":"Don'\''t forget to add today'\''s expenses before the day ends."},
              "url":"https://naveensiriveri24-jcoder.github.io/"
            }'
